# Generated by Django 2.0.2 on 2018-05-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_event_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Database.Event'),
        ),
    ]
