# Generated by Django 2.0.2 on 2018-05-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_objective_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Database.Question')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='visitedObjectives',
            field=models.ManyToManyField(blank=True, null=True, to='Database.Objective'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='Database.Question'),
        ),
    ]
