# Generated by Django 2.0.2 on 2018-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20180517_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anwser',
            name='question',
        ),
        migrations.AddField(
            model_name='anwser',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
